# Generated by Django 3.2.12 on 2024-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="user",
        ),
        migrations.AddField(
            model_name="coupon",
            name="msg",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
