# Generated by Django 3.2.12 on 2024-03-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_auto_20240307_0456"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet_list",
            name="msg",
            field=models.TextField(null=True),
        ),
    ]
