# Generated by Django 3.2.12 on 2024-03-02 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("my_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="cart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("book_quantity", models.IntegerField(null=True)),
                ("cart_total", models.IntegerField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_admin.myprodect",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
