# Generated by Django 3.2.12 on 2024-03-06 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin", "0002_alter_myprodect_date_added"),
        ("cart", "0002_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_products",
                to="my_admin.myprodect",
            ),
        ),
    ]
