# Generated by Django 3.2.12 on 2024-03-03 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myprodect",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
