# Generated by Django 5.0.7 on 2024-08-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_alter_myprodect_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincategory',
            name='offer',
        ),
    ]
