# Generated by Django 3.2.12 on 2024-03-03 12:05

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_expect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="expect",
            field=models.DateField(default=order.models.default_expect_date),
        ),
    ]
