# Generated by Django 3.2.12 on 2024-03-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0002_auto_20240307_1451"),
        ("order", "0005_alter_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coupon.coupon",
            ),
        ),
    ]
