# Generated by Django 3.2.12 on 2024-03-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_order_coupon_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Ordered", max_length=150),
        ),
    ]
